wants:
  mongo: true

secrets:
  - SECRET
  - GROUNDTRUTHSECRET
  - GRAPHQLAUTH

env:
  GROUNDTRUTHID: 9a76e3279d70edc9896ebb003ab7adcc3b1dcddafdaa780018941bec39b43bc8
  GROUNDTRUTHURL: https://login.hack.gt
  GRAPHQLURL: https://registration.2021.hack.gt/graphql
  ISPRODUCTION: true
  HOST_URL: teamformation.2021.hack.gt
