git:
  branch: master

wants:
  mongo: true

secrets:
  - SECRET
  - GROUNDTRUTHID
  - GROUNDTRUTHSECRET
  - GRAPHQLAUTH
  - CLIENT_ID
  - CLIENT_SECRET
  - SIGNING_SECRET
  - OAUTH_TOKEN


env:
  GROUNDTRUTHURL: https://login.hack.gt
  GRAPHQLURL: https://registration.2020.hack.gt/graphql
  ISPRODUCTION: true
  TEAM_ID: T01AUT83XST
  HOST_URL: teamformation.hack.gt
